resources:
- name: resource-cypress
  type: git
  source:
    uri: https://github.com/github-patrick/cypress.git
    branch: master

jobs:
- name: job-automation-cypress
  public: true
  plan:
  - get: resource-cypress
    trigger: true
  - put: docker-image
    params:
      build: resource-cypress/concourse/

#  - task: cypress-test
#    file: resource-cypress/concourse/task-cypress-automation.yml
