resources:
- name: resource-cypress
  type: git
  source:
    uri: https://github.com/github-patrick/cypress.git
    branch: master

jobs:
- name: job-automation-cypress
  public: true
  plan:
  - get: resource-cypress
    trigger: true
  - task: cypress-test
    file: resource-tutorial/tutorials/basic/task-hello-world/task_hello_world.yml
    file: resource-cypress/concourse/task-cypress-automation.yml
