resources:
- name: resource-cypress
  type: git
  source:
    uri: https://github.com/github-patrick/cypress.git
    branch: master

- name: cypress-docker-image
  type: docker-image
  source:
    email: developer.sessions@gmail.com
    username: dockerdozens
    password: testing123
    repository: dockerdozens/cypress-automation

jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: resource-cypress
  - put: cypress-docker-image
    params:
      build: resource-cypress


- name: job-automation-cypress
  public: true
  plan:
  - get: resource-cypress
    trigger: true
  - task: cypress-test
    file: resource-cypress/concourse/task-cypress-automation.yml
