---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cypress/base, tag: 8}

image_resource:
  type: docker-image
  source: {repository: httpd, tag: alpine}

inputs:
- name: resource-cypress

run:
  path: resource-cypress/concourse/task_run_tests.sh