---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: 1.9-alpine}

inputs:
- name: resource-cypress


run:
  path: resource-tutorial/tutorials/basic/job-inputs/task_run_tests.sh