---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: 8

outputs:
- name: workspace

inputs:
- name: resource-cypress

run:
        path: /bin/bash
        args:
        - -c
        - |
          output_dir=workspace

          cat << EOF > "${output_dir}/Dockerfile"
          FROM cypress/base:10 as TEST
          WORKDIR /app
          COPY package.json .
          RUN npm install
          COPY cypress cypress
          COPY cypress.json .
          RUN npx cypress run
          EOF

           cp -R ./ "${output_dir}/."



#run:
#  path: resource-cypress/concourse/task_run_tests.sh