---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dockerdozens/cypress-automation

inputs:
  - name: resource-cypress


run:
  path: resource-cypress/concourse/task_run_tests.sh