---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dockerdozens/cypress-automation
       run:
          path: /bin/bash
          args:
          - -c
          - |
              npx cypress run