---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dockerdozens/cypress-automation

       run:
            path: sh
            args:
            - -exc
            - |
                npx cypress run